name: learn-github-actions
on:
  push:
    # This action will only run when .py files are modified in src/ or tests/ directories
    # AND when pushed to the main branch
    paths:
      - 'src/**/**.py'
      - 'tests/**.py'
    branches:
      - main
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      # with:
      #   node-version: '14'
      # - run: npm install -g bats
      # - run: bats -v
      - run: echo "Running github action to check python version"
      - run: python --version