name: learn-github-actions
on:
  push:
    paths:
      - 'src/**/**.py'
      - 'tests/**.py'
    paths-ignore:
      - '.vscode/**'
      - '.gitignore'
      - 'pyproject.toml'
      - 'README.md'
      - 'requirements*.txt'
      - 'setup.cfg'
    branches:
      - main
jobs:
  check-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - uses: actions/setup-node@v3
      # with:
      #   node-version: '14'
      # - run: npm install -g bats
      # - run: bats -v
      - run: echo "Running github action to check python version"
      - run: python --version